# Generated by Django 4.1.1 on 2022-09-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_alter_item_options_item_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='api.item', verbose_name='Предметы'),
        ),
    ]
