# Generated by Django 4.1.1 on 2022-09-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_options_remove_item_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
